package com.trajectiv.dl.enums;

public enum FeatureKey {
    CV_BUILDER,
    CV_EXPORT_PDF,
    CV_EXPORT_DOCX,
    CV_TEMPLATE_PREMIUM,
    CV_OFFER_ANALYSIS_BASIC,
    CV_OFFER_ANALYSIS_AI,
    ATS_CHECK_BASIC,
    ATS_CHECK_ADVANCED,
    INTERVIEW_SIMULATION_LIGHT,
    INTERVIEW_SIMULATION_FULL,
    ADVANCED_ANALYTICS,

    ORGANIZATION_COHORTS,
    ORGANIZATION_REPORTING,
    TRAINER_FEEDBACK,
    PRIVATE_CONTENT_LIBRARY,
    AI_CREDITS_MONTHLY_LIMIT
}
