package com.trajectiv.dl.enums.audit;

public enum AuditAction {

    ORGANIZATION_MEMBER_ROLE_CHANGED,
    ORGANIZATION_MEMBER_SUSPENDED,
    ORGANIZATION_MEMBER_REACTIVATED,
    ORGANIZATION_MEMBER_REMOVED,

    ORGANIZATION_INVITATION_CREATED,
    ORGANIZATION_INVITATION_REVOKED,
    ORGANIZATION_INVITATION_RESENT,
    ORGANIZATION_INVITATION_ACCEPTED
}