package com.trajectiv.bll.exceptions;

import org.springframework.http.HttpStatus;

public enum BusinessErrorCode {

    INVALID_AUTHENTICATED_USER_CLAIMS(HttpStatus.UNAUTHORIZED),

    USER_PROFILE_NOT_INITIALIZED(HttpStatus.INTERNAL_SERVER_ERROR),
    USER_SUBSCRIPTION_NOT_INITIALIZED(HttpStatus.INTERNAL_SERVER_ERROR),
    USER_AI_CREDIT_WALLET_NOT_INITIALIZED(HttpStatus.INTERNAL_SERVER_ERROR),

    ONBOARDING_REQUIRED_FIELDS_MISSING(HttpStatus.BAD_REQUEST),

    USER_FILE_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMPTY_FILE(HttpStatus.BAD_REQUEST),
    FILE_TOO_LARGE(HttpStatus.BAD_REQUEST),
    UNSUPPORTED_FILE_TYPE(HttpStatus.BAD_REQUEST),

    SUBSCRIPTION_REQUIRED(HttpStatus.FORBIDDEN),
    AI_CREDITS_EXHAUSTED(HttpStatus.FORBIDDEN),

    AVATAR_CUSTOMIZATION_ALREADY_EXISTS(HttpStatus.CONFLICT),
    AVATAR_CUSTOMIZATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_AVATAR_CUSTOMIZATION(HttpStatus.BAD_REQUEST),
    USER_SUBSCRIPTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORGANIZATION_SUBSCRIPTION_NOT_FOUND(HttpStatus.NOT_FOUND),

    PLAN_NOT_FOUND(HttpStatus.NOT_FOUND),
    PLAN_ENTITLEMENT_CONFIGURATION_INVALID(
            HttpStatus.INTERNAL_SERVER_ERROR
    ),

    USER_AI_CREDIT_WALLET_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORGANIZATION_AI_CREDIT_WALLET_NOT_FOUND(
            HttpStatus.NOT_FOUND
    ),

    ORGANIZATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORGANIZATION_MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND),

    ENTITLEMENT_NOT_GRANTED(HttpStatus.FORBIDDEN),

    ORGANIZATION_SLUG_ALREADY_EXISTS(HttpStatus.CONFLICT),
    ORGANIZATION_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    ORGANIZATION_NOT_ACTIVE(HttpStatus.CONFLICT),

    ORGANIZATION_INVITATION_NOT_FOUND(HttpStatus.NOT_FOUND),
    ORGANIZATION_INVITATION_ALREADY_PENDING(HttpStatus.CONFLICT),
    ORGANIZATION_INVITATION_EXPIRED(HttpStatus.GONE),
    ORGANIZATION_INVITATION_REVOKED(HttpStatus.CONFLICT),
    ORGANIZATION_INVITATION_ALREADY_ACCEPTED(HttpStatus.CONFLICT),
    ORGANIZATION_INVITATION_EMAIL_MISMATCH(HttpStatus.FORBIDDEN),
    ORGANIZATION_INVITATION_EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN),
    ORGANIZATION_MEMBER_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_ORGANIZATION_INVITATION(HttpStatus.BAD_REQUEST),

    USER_NOT_FOUND(HttpStatus.NOT_FOUND);

    private final HttpStatus httpStatus;

    BusinessErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }
}
